version: '3.8'

services:
  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./hosts:/usr/local/hosts
    depends_on:
      - flaskapp1
      - flaskapp2
      - flaskapp3

  flaskapp1:
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    volumes:
      - ./flaskapp/logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  flaskapp2:
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    volumes:
      - ./flaskapp/logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  flaskapp3:
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    volumes:
      - ./flaskapp/logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/logs:/var/log/mongodb
